from pydantic import BaseModel, Field
from typing import Optional
from uuid import UUID
from datetime import datetime


class CreateQRCode(BaseModel):
    """
    Request model for creating QR code with frontend-provided UUID.

    IMPORTANT: The UUID is generated by the frontend using crypto.randomUUID(),
    not by the backend. The backend accepts this UUID and creates the record.
    """
    id: UUID = Field(..., description="Frontend-generated UUID for the QR code")
    name: Optional[str] = Field(None, max_length=100, description="QR code name (e.g., 'Van 1 - Louisville')")
    airlines: Optional[list[str]] = Field(None, description="Allowed airline codes (null = all airlines)")
    metadata: Optional[dict] = Field(None, description="Additional metadata for analytics")


class UpdateQRCode(BaseModel):
    """Request model for updating QR code."""
    status: Optional[str] = Field(None, description="QR code status: 'active' or 'disabled'")
    name: Optional[str] = Field(None, max_length=100, description="QR code name")
    airlines: Optional[list[str]] = Field(None, description="Allowed airline codes")


class QRCodeResponse(BaseModel):
    """Response model for QR code."""
    id: str
    organization_id: str
    location_id: str
    name: Optional[str]
    airlines: Optional[list[str]]
    status: str
    scan_count: int
    last_scanned_at: Optional[str]
    created_at: str
    updated_at: str

    model_config = {"from_attributes": True}
