from psqlmodel import PSQLModel, table, Column
from psqlmodel.orm.types import uuid, jsonb, timestamptz
from psqlmodel.utils import now


class QRCodeStatus:
    """QR code status constants."""
    ACTIVE = "active"
    DISABLED = "disabled"


@table("qr_codes", schema="entities")
class QRCode(PSQLModel):
    """
    QR codes for crew lookup functionality.

    IMPORTANT: The QR code UUID is generated by the FRONTEND, not the backend.
    The frontend generates a UUID, displays it in the UI, and includes it in
    the SQL instructions for the user to execute manually.

    Each QR code is associated with an organization and location,
    allowing crew members to quickly access van pickup information
    by scanning a physical QR code.
    """

    id: uuid = Column(
        primary_key=True
        # NO default - UUID comes from frontend
    )

    organization_id: uuid = Column(
        foreign_key="entities.organizations.id",
        on_delete="CASCADE",
        nullable=False,
        index=True
    )

    location_id: uuid = Column(
        foreign_key="entities.locations.id",
        on_delete="CASCADE",
        nullable=False,
        index=True,
        unique=True  # Exactly 1 QR per Location
    )

    # Human-readable name for management (e.g., "Van 1 - Louisville")
    name: str = Column(
        max_len=100,
        nullable=True
    )

    # List of airline codes allowed for this QR (null = all allowed)
    # Example: ["WN", "AA", "DL"]
    airlines: jsonb = Column(
        nullable=True,
        default=None
    )

    # Status of the QR code
    status: str = Column(
        max_len=20,
        nullable=False,
        default=QRCodeStatus.ACTIVE,
        index=True
    )

    # Metadata for analytics (e.g., physical location, van number, etc.)
    metadata: jsonb = Column(
        nullable=True,
        default=None
    )

    # Timestamps
    created_at: timestamptz = Column(
        default=now,
        nullable=False,
        index=True
    )

    updated_at: timestamptz = Column(
        default=now,
        nullable=False
    )

    # Track last time QR was scanned (for analytics)
    last_scanned_at: timestamptz = Column(
        nullable=True,
        default=None
    )

    # Scan count for analytics
    scan_count: int = Column(
        nullable=False,
        default=0
    )
